---
- name: install apache2
  hosts: test
  become: yes
  remote_user: root

  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: restart apache2 service
    service:
      name: apache2
      state: restarted

  - name: chnage apache2 service port number to 81
    shell: "sed -i 's/Listen 82/Listen 81/g' /etc/apache2/ports.conf"
    notify:
    - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
