---
- name: install apache2
  hosts: test
  become: yes
  remote_user: root

  tasks:
  - name: install apache on rhel
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "rhel"

  - name: install apache on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
